server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /front {
        return 301 /front/;
    }

    location /front/ {
        try_files $uri $uri/ /front/index.html;
    }
}
