name: Build and Deploy with MicroK8s

on:
  push:
    branches: [main]

jobs:
  build-and-publish:
    name: Build and Push Image to GHCR
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Mostrar rama actual
        run: echo "Rama actual: ${{ github.ref }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          IMAGE: ghcr.io/${{ github.repository }}
        run: |
          IMAGE_LOWER=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          docker build -t ${IMAGE_LOWER}:latest -t ${IMAGE_LOWER}:${{ github.sha }} .
          docker push ${IMAGE_LOWER}:latest
          docker push ${IMAGE_LOWER}:${{ github.sha }}

  deploy-onpremise:
    name: Deploy on MicroK8s On-Premise
    runs-on: main
    needs: build-and-publish

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Apply Kubernetes manifests
        run: sudo microk8s kubectl apply -f k8s.yaml

      - name: Update image to latest SHA
        run: |
          sudo microk8s kubectl set image deployment/angular-web \
            angular-web=ghcr.io/advsnts/angular-web:${{ github.sha }} \
            -n grupo11

      - name: Wait for rollout
        run: sudo microk8s kubectl rollout status deployment/angular-web -n grupo11